spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 5000
          service-product:
            connect-timeout: 2000
            read-timeout: 5000
            request-interceptors:
              - edu.wust.qrz.interceptor.XTokenInterceptor
            # 配置重试机制
#            retryer: feign.Retryer.Default


feign:
  sentinel:
    enabled: true

