spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 5000
          service-product:
            connect-timeout: 2000
            read-timeout: 2000

