spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - Path=/api/services/order/**
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/services/product/**

        - id: bing-route
          uri: https://www.bing.com
          predicates:
            - Path=/search/**
            - name: Query
              args:
                param: q
                regexp: test
            - Vip=user, qrz
