spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://service-order
          predicates:
            - Path=/api/services/order/**
          filters:
            - RewritePath=/api/services/?(?<segment>.*), /$\{segment}

        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/services/product/**
          filters:
            - RewritePath=/api/services/?(?<segment>.*), /$\{segment}

        - id: bing-route
          uri: https://www.bing.com
          predicates:
            - Path=/search/**
            - Query=q,test
            - Vip=user, qrz
